# =============================================================
# Stage 1 - deps
#   Install all dependencies (frozen lockfile for reproducible
#   builds). Kept as a separate layer so rebuilds triggered by
#   source changes don't re-install node_modules.
# =============================================================
FROM oven/bun:1-alpine AS deps

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# =============================================================
# Stage 2 - builder
#   Compile the Next.js production bundle.
#   We enable the standalone output mode so the final runner
#   image does NOT need node_modules at all.
# =============================================================
FROM oven/bun:1-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1

RUN bun run build

# =============================================================
# Stage 3 - runner (web server)
#   Minimal image that serves the Next.js app via node server.js
#   (the standalone entry-point generated by Next.js).
# =============================================================
FROM oven/bun:1-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# Non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# Standalone output + static assets
COPY --from=builder /app/public                        ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static     ./.next/static

# argon2 ships a native addon; copy the pre-built binary
COPY --from=builder /app/node_modules/argon2           ./node_modules/argon2

USER nextjs

EXPOSE 3000

# standalone mode emits a self-contained server.js
CMD ["node", "server.js"]

# =============================================================
# Stage 4 - worker
#   Runs the background grading-job poller.
#   Needs access to the Docker daemon (bind-mount the host socket
#   or use Docker-in-Docker) so it can spawn sandboxed containers.
# =============================================================
FROM oven/bun:1-alpine AS worker

WORKDIR /app

# Docker CLI is required to launch code-execution containers
RUN apk add --no-cache docker-cli

ENV NODE_ENV=production

# Copy only what the worker script needs at runtime
COPY --from=deps    /app/node_modules    ./node_modules
COPY --from=builder /app/scripts         ./scripts
COPY --from=builder /app/server          ./server
COPY --from=builder /app/lib             ./lib
COPY --from=builder /app/db              ./db
COPY --from=builder /app/tsconfig.json   ./tsconfig.json
COPY --from=builder /app/package.json    ./package.json

CMD ["bun", "scripts/process-grading-jobs.ts"]
