# =============================================================
# Stage 1 - deps
#   Install all dependencies (frozen lockfile for reproducible
#   builds). Kept as a separate layer so rebuilds triggered by
#   source changes don't re-install node_modules.
# =============================================================
FROM oven/bun:1-alpine AS deps

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# =============================================================
# Stage 2 - builder
#   Compile the Next.js production bundle.
#   We enable the standalone output mode so the final runner
#   image does NOT need node_modules at all.
# =============================================================
FROM oven/bun:1-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1

RUN bun run build

# =============================================================
# Stage 2b - migrator
#   One-shot release image. Production schema changes come only
#   from the checked-in Drizzle migrations.
# =============================================================
FROM deps AS migrator

WORKDIR /app

COPY db/ ./db/
COPY scripts/migrate.ts ./scripts/migrate.ts
COPY drizzle.config.ts tsconfig.json package.json ./

ENV NODE_ENV=production
CMD ["bun", "scripts/migrate.ts"]

# =============================================================
# Stage 3 - runner (web server)
#   Minimal image that serves the Next.js app via node server.js
#   (the standalone entry-point generated by Next.js).
# =============================================================
FROM oven/bun:1-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# Non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# Standalone output + static assets
COPY --from=builder /app/public                        ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static     ./.next/static

# argon2 ships a native addon; copy the pre-built binary
COPY --from=builder /app/node_modules/argon2           ./node_modules/argon2

USER nextjs

EXPOSE 3000

# standalone mode emits a self-contained server.js
CMD ["bun", "server.js"]

# =============================================================
# Stage 4a - worker-builder
#   Compiles the worker script + deps into a standalone binary
#   so the final worker image needs no node_modules at all.
# =============================================================
FROM oven/bun:1-alpine AS worker-builder

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY scripts/ ./scripts/
COPY server/  ./server/
COPY lib/     ./lib/
COPY modules/ ./modules/
COPY db/      ./db/
COPY tsconfig.json package.json ./

RUN bun build ./scripts/process-grading-jobs.ts \
      --compile \
      --conditions react-server \
      --target bun-linux-x64-musl \
      --outfile /app/worker-bin

# =============================================================
# Stage 4b - worker
#   Minimal image that runs the compiled grading-job poller.
#   Needs Docker CLI to spawn sandboxed code-execution containers.
# =============================================================
FROM alpine:3.20 AS worker

WORKDIR /app

RUN addgroup --system --gid 1001 worker && \
    adduser  --system --uid 1001 --ingroup worker worker

RUN apk add --no-cache docker-cli libstdc++ libgcc

COPY --from=worker-builder /app/worker-bin ./worker

USER worker
CMD ["./worker"]
