export const IDEMPOTENCY_KEY_HEADER = "x-idempotency-key";

export const ErrorCode = {
  RATE_LIMITED: "rate_limited",
  CONFLICT: "conflict",
  NOT_FOUND: "not_found",
  UNAUTHORIZED: "unauthorized",
  FORBIDDEN: "forbidden",
  VALIDATION: "validation",
  UNAVAILABLE: "unavailable",
  INTERNAL: "internal",
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const Messages = {
  // generic / validation
  invalidRequest: "We couldn't read your request. Please check your details and try again.",
  invalidInviteCode: "That invite code doesn't look right.",
  somethingWrong: "Something went wrong. Please try again.",
  rateLimited: "Too many attempts. Please try again later.",
  // idempotency
  refreshRetry: "Please refresh the page and try again.",
  requestConflict: "This request was already sent with different details. Please refresh and try again.",
  requestInProgress: "You already have a request running. Please wait for it to finish.",
  idempotencyUnresolved: "Something went wrong. Please try again.",
  // auth
  unauthorized: "Please sign in to continue.",
  forbidden: "You don't have permission to do that.",
  invalidCredentials: "That username or password doesn't match.",
  usernameTaken: "That username is already taken.",
  userNotFound: "We couldn't find that account.",
  invalidUsername: "That username isn't valid.",
  currentPasswordIncorrect: "Your current password is incorrect.",
  resetLinkInvalid: "This reset link is invalid or has expired.",
  // not-found (resources)
  questionNotFound: "We couldn't find that question.",
  classroomNotFound: "We couldn't find that classroom.",
  assignmentNotFound: "We couldn't find that assignment.",
  submissionNotFound: "We couldn't find that submission.",
  testcaseNotFound: "We couldn't find that test case.",
  languageNotFound: "We couldn't find that language.",
  gradingJobNotFound: "We couldn't find that grading task.",
  // code / grader
  codeRequired: "Please write some code first.",
  languageRequired: "Please choose a language.",
  codeTooLong: (max: number) => `Your code is too long (max ${max} characters).`,
  languageNotAllowed: "That language isn't available for this question.",
  languageNotSupported: "That language isn't supported.",
  languageUnavailable: "That language isn't available right now.",
  questionNotReady: "This question isn't ready yet. Please try again later.",
  gradingUnavailable: "Code running is temporarily unavailable. Please try again later.",
  gradingDisabled: "Code running is not available.",
  gradingMisconfigured: "Code running isn't set up correctly.",
  // admin language config
  langMissingFileExt: "That language is missing its file extension setting.",
  langMissingDockerImage: "That language is missing its run image setting.",
  langMissingRunCommand: "That language is missing its run command setting.",
  langInvalidImage: "Enter a valid image name, like python:3.12-alpine.",
  langDiagnosticsCommandRequired: "Add a diagnostics command when using the compiler format.",
  publishNeedsTestcase: "Add at least one test case before publishing.",
  // upload / avatar
  avatarUnavailable: "Profile pictures aren't available right now.",
  noFile: "No file was uploaded.",
  imageOnly: "Only image files are allowed.",
  fileTooLarge: "Maximum file size is 5MB.",
  // contextual fallbacks (used in catch blocks)
  unableToCreateQuestion: "We couldn't create the question. Please try again.",
  unableToSaveQuestion: "We couldn't save the question. Please try again.",
  unableToUpdateQuestion: "We couldn't update the question. Please try again.",
  unableToDeleteQuestion: "We couldn't delete the question. Please try again.",
  unableToCreateClassroom: "We couldn't create the classroom. Please try again.",
  unableToJoinClassroom: "We couldn't join that classroom. Please try again.",
  unableToCreateAssignment: "We couldn't create the assignment. Please try again.",
  unableToCreateLanguage: "We couldn't create the language. Please try again.",
  unableToUpdateLanguage: "We couldn't update the language. Please try again.",
  unableToDeleteLanguage: "We couldn't delete the language. Please try again.",
  unableToSaveTestcase: "We couldn't save the test case. Please try again.",
  unableToUpdateTestcase: "We couldn't update the test case. Please try again.",
  unableToDeleteTestcase: "We couldn't delete the test case. Please try again.",
  unableToRunCode: "We couldn't run your code. Please try again.",
  unableToSubmit: "We couldn't submit your solution. Please try again.",
  unableToRejudge: "We couldn't rejudge that submission. Please try again.",
  unableToUpdateProfile: "We couldn't update your profile. Please try again.",
  unableToUpdateUsername: "We couldn't update your username. Please try again.",
  unableToChangePassword: "We couldn't change your password. Please try again.",
  unableToResetPassword: "We couldn't reset the password. Please try again.",
  unableToGenerateResetLink: "We couldn't generate a reset link. Please try again.",
  unableToUploadAvatar: "We couldn't upload your picture. Please try again.",
  unableToSaveProfilePicture: "We couldn't save your profile picture. Please try again.",
  unableToListUsers: "We couldn't load the users. Please try again.",
  unableToComputeDiagnostics: "We couldn't check your code. Please try again.",
} as const;
